---
output:
  pdf_document: default
  html_document: default
---
# Humanistic Perspective {#humanistic}

In this section, we briefly introduce ideas from science and technology studies (STS), which track habits of thought that have fundamentally shaped the ways in which we think about and study toxicity. Our goal, here, is to contextualize exposure mixture studies — the motivation for this thesis — within larger regimes of knowledge production. We aim to recognize the limitations in current norms of understanding toxicity in order to inform research that more accurately reflects the complex realities of communities who bear the burdens of toxic exposure. 

Modern scientific thinking encourages the onlooker to see objects in the world as distinct entities. For instance, when we talk about chemicals, we tend to talk about them as disconnected molecules: lead, mercury, per- and polyfluoroalkyl substances, etc. Clouds of pollution are conceived through their individual components, each of which becomes separated from its surroundings through the lenses of our imaginations [@myers_rendering_2015]. While it is easy to accept this ontology as inevitable, its origins can be located in the history of chemistry. The Industrial Revolution first turned chemistry into a profitable field, leading practitioners to become keenly interested in how structural representations of chemicals could be most useful for industrial and corporate technoscientific disciplines [@bensaude-vincent_history_1996]. Reducing chemical mixtures amidst complex environments down into discrete molecules made the quantification of their effects simpler — certain side effects or relations could be masked or hidden in technical reports. Such reports were then used by industrial lobbyists as evidence for reducing or withholding environmental regulations [@murphy_alterlife_2017]. 

These lines of thinking have filtered out of industry and into scientific studies of environmental health, which have historically been permeated by a focus on studying single chemicals [@alaimo_bodily_2010]. The end goal has often been to obtain mechanistic explanations of their modes of toxicity. By isolating attention to a single chemical entity within a purely biological framework, one can simplify the problem; but, in so doing, one also captures only a narrow sliver of the complex social and physical realities of exposure [@murphy_uncertain_2004]. This is not to dismiss such studies or their contributions when, in fact, they are necessary for understanding the mechanisms of exposure. Rather, we hope to acknowledge that there exist additional possibilities for the study of exposures when we shift perspective away from isolated molecules and into chemical relations. 

We start by recognizing that an object cannot exist without also taking on relations to other beings — existence implies relationality. This concept of relationality disrupts the notion that objects can be bounded, the archetypal project of intellectual modernity. Indeed, the modern Cartesian split between body and mind idealizes humanness as a quality that is separable from the physical human form [@venn_individuation_2010]. In other words, the ideal human can be defined not by her corporeal body, or its physical relations to the environment, but instead by her intellect. Modernity insists that humans are not enmeshed in relations. However, toxicity is embodied in materials and in living beings and, as such, is inherently relational [@theriault_toxic_2021]. Evidence of toxic exposure, then, reinforces the dependence of the human on its corporeal form. 

This is a problematic way to view chemical relations. Bodies that bear the burden of toxicity are cast as more porous to their environments, and thus less qualified or worthy of humanness [@roberts_what_2017]. Such designations often take on a racial valence; structural preconditions place racial minorities in closer proximity to toxins, creating co-constituted geographies of toxicity and racialization [@packer_becoming_2022]. As a result, toxicity becomes embedded in racial hierarchies that qualify racialized groups as less human. Relationality encourages us to move away from this damaging epistemology. To this, we call on Michelle Murphy's definition of *alterlife*, which "names life already altered... [and] being in the contradictions of existing in worlds that demand chemical exposures as the conditions for eating, drinking, breathing," [-@murphy_alterlife_2017, p. 497]. Alterlife acknowledges that man-made chemical entities persist in every living being — it is no longer possible to live without being exposed. Moreover, it also highlights that the geographies of chemical exposures are inevitably mediated by unequal social conditions. Human life is alterlife. We are all bound together by a web of complex and unequal chemical relations. 

It is critical that we explore modes of co-habitation that make these toxic conditions more livable. This task does not fall purely to science — other forms of knowledge are crucial for navigating the chemical hazards of our everyday life [@nguyen_breathless_2020; @shapiro_attuning_2015]. The responsibility of science, though, is to become aware of how such hazards are lived and experienced. STS scholars have advocated for a departure from linear thinking, which singles out isolated causes, chemicals, and bodies [@murphy_uncertain_2004; @roberts_what_2017; @lock_anthropology_2018]. We argue that the methods for exposure mixtures examined in this thesis take us one step closer to this goal. In particular, exposure mixtures account for the realities of co-occuring chemical compounds and their non-linear effects. Testing for interactions between chemicals acknowledges that the relationality of these molecules with each other might affect their modes of action. In so doing, exposure mixtures push us to think beyond the limiting constructs of boundedness and isolation. 

We also consider potential interactions between sociodemographic covariates and chemical exposures, a previously understudied form of interaction. As we have discussed, chemicals — despite being inanimate objects — are not fully separable from the societal context in which they exist. Pollutants become entangled in bodies that are themselves entangled in social relations. We link this idea to practices in social epidemiology, which posit that one’s health is embodied within structural conditions [@krieger_theories_2001; @krieger_epidemiology_2011]. In the context of exposure studies, this requires acknowledging that the effects of chemical exposure can be modulated along lines of race, class, and other discriminative categories that privilege certain groups over others.

Still, there is more work to do. We make a multitude of assumptions when describing human livelihoods with numbers and models. For instance, the race variable that we use attempts to capture the full lived experience of racism within five categories. Moreover, the studies of exposure that we focus on can also be forms of damage-centered research, which @tuck_suspending_2009 defines as work that documents unjust harms enacted against communities. While aimed at accountability and justice, such research can also unintentionally perpetuate norms of thinking about certain communities as inherently damaged. These harms can arise when we start to unconsciously attribute toxicity as the defining feature of the target populations of our studies, and toxic exposure becomes the primary reason that they are valuable to science. To remedy this, the research community must explore collaborative forms of inquiry that engage and empower communities in the research process, through a framework that @tuck_suspending_2009 describes as "desire-centered." And, there are certainly other considerations that we have missed. So, we hope that this is just the start of a conversation that continues to contend with how scientific studies of exposure can help us better make sense of our new toxic realities.  

