# Conclusion {-}

We will continue to encounter mixtures of novel chemical entities in our day-to-day lives. Statistical studies of the health risks associated with exposure to chemical pollutants are critical for making modern toxic landscapes more habitable. Historically, the focus of risk assessments has been to identify the toxicity of single chemicals. However, as discussed in Chapter \@ref(humanistic), such studies stem from habits of thought which seek to associate outcomes with isolated causes. An approach that considers the joint effects of multiple chemical pollutants — exposure mixtures — is more representative of reality, and also more likely to be protective of human health. However, exposure mixture studies come with a host of statistical challenges. This thesis focuses on the task of detecting non-additive interactions between exposures and sociodemographic covariates. 
 
<!-- As such, expanding the focus of analysis to multiple chemicals is -->

Beyond posing an interesting statistical estimation challenge, interactions are also important for accurately estimating health risk from exposure mixtures and informing policymakers about the potential benefits of environmental regulations. In Chapter \@ref(bayes), we introduce two flexible Bayesian regression models, BKMR and BSR, which both have the capacity to detect interactions. We discuss how the two models take different approaches to estimation. BKMR employs kernel machine regression, a nonparametric modeling technique that can flexibly capture complex exposure-response relationships and, as such, allows for non-additive interactions between exposures. BSR employs spline regression, a semiparametric modeling technique, in a model formulation that explicitly incorporates interaction terms. This parameterization of interaction terms makes BSR's inferential approach for interactions more formal than BKMR's. 

Our simulation study in Chapter \@ref(sims) compares the ability of BKMR and BSR to detect interactions between chemicals. Our results emphasize the challenges of detecting interactions. In general, BKMR and BSR had lower sensitivites compared to a multiple linear regression with the true form of interactions specified. Still, we were able to achieve high sensitivities using BKMR and BSR to detect interactions between univariately significant chemicals. Sensitivity for univariately insignificant chemicals was much lower, and these interactions were only detected when univariate signals were also detected. Multicollinearity between interacting chemicals likely reduces sensitivity, and three-way interactions are generally very difficult to detect. Increasing the sample size from around 250 to 1000 in our simulations considerably increased sensitivity for interactions.

<!-- There can be differences in the performance of BKMR and BSR, but neither consistently outperforms the other. Thus, as BKMR is generally more reliable for univariate effects, and also computationally less intensive, we recommend BKMR for  -->

We conclude that BKMR and BSR are generally comparable for detecting interactions between chemicals, as neither consistently outperforms the other. For future studies of interactions in exposure mixture studies using Bayesian models, we recommend increasing the target sample size in study design, in order to increase power for interactions. Then, for data analysis, we recommend using BKMR first to identify both univariate effects and potential interactions with visual diagnostic plots. BKMR is generally more sensitive to univariate signals, more reliable in smaller sample sizes, and also computationally less intensive. Then, we recommend using BSR to verify these results, as it tends to have lower false discovery rates for univariate effects and also provides a more formal framework of inference for any potential interactions. As most interactions were only detected when the chemicals were also univariately significant, limiting the search space to those chemicals with univariate PIPs greater than 0.5 should generally capture all significant interactions. 

We also assessed interactions between chemicals and a categorical race covariate. Testing for such interactions can identify cases where certain groups may experience excess harmful effects of exposure due to discriminative social and structural conditions. However, we found that it was generally very difficult to detect such interactions using stratified BKMR and BSR models. Even in large sample sizes, and when the differential effect of exposure was in the largest race category, sensitivity was still very low. As such, we highlight that current Bayesian methods are under-powered for detecting potential interactions between categorical covariates and an exposure. 

There are multiple areas for future simulation studies that arise from our findings. First, it would be beneficial to complete the full analyses for scenarios considered in our simulation by obtaining false discovery rates for three-way interactions and interactions between race and Hg, as well as recording run-times for the stratified BSR models. Next, considering interactions between collinear chemicals that are, themselves, univariately significant, could strengthen our finding that multicollinearity reduces sensitivity for interactions. This is also the case for three-way interactions. Identifying a method for constructing confidence intervals on the estimated magnitude of response for BSR would allow us to conduct inference on stratified BSR models for interactions between a categorical covariate and an exposure. Finally, our simulated datasets included 10 chemicals and 4 covariates, but exposure mixture studies can often include many more variables. Future simulations could consider how sensitivity for interactions changes in higher-dimensional data. 

Overall, this thesis summarizes the current capabilities of modern Bayesian statistical methods for characterizing complex interactions in exposure mixture studies. The flexibility of recently developed techniques enables models to successfully identify interactions in noisy and high-dimensional data. However, we also highlight areas where current methods fall short, particularly for interactions between covariates and exposure. Thus, it is important that we continue to develop methods that account for the unique statistical challenges of exposure mixtures, in order to progress toward a study of exposure that better considers how bodies are related to the environment and to each other. 

